// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system 
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <vector>

static void msg(const char *msg){
	fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg){
	fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg){
	fprintf(stderr, "[%d] %s\n", errno, msg);	
	abort();
}

static void fd_set_nb(int fd){
	errno = 0;
	int flags = fcntl(fd, F_GETFL, 0);
	if (errno){
		die("fcntl error");
		return;
	}
	flags |= O_NONBLOCK;

	errno = 0;
	(void)fcntl(fd, F_SETFL, flags);
	if(errno){
		die("fcntl error");
	}
}

const size_t k_max_msg = 32 << 20; // likerly larger tah the kernel buffer


struct Conn {
	int fd = -1;
	// application's intention, for the event loop
	bool want_read = false;
	bool want_write = false;
	bool want_close = false;
	// buffered input and output
	std::vector<uint8_t> incoming; //data to be parsed by the application
	std::vector<uint8_t> outgoing; // responses generated by the application

};

// append to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
	buf.insert(buf.end(), data, data + len);
}


// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t n){
	buf.erase(buf.begin(), buf.begin() + n);
}

// application callback when the listening socket is ready
static Conn *handle_accept(int fd){
	// accept
	struct sockaddr_in client_addr = {};
	socklen_t addrlen = sizeof(client_addr);
	int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
	if(connfd < 0){
		msg_errno("accept() error");
		return NULL;
	}
	uint32_t ip = client_addr.sin_addr.s_addr;
	fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
					ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
					ntohs(client_addr.sin_port)
			);
	// set the new connection fd t nonblocking mode
	fd_set_nb(connfd);
	// create a `struct Conn`
	Conn *conn = new Conn();
	conn->fd = connfd;
	conn->want_read = true;
	return conn;	
}

/*
 * handle multiple requests without concurrency
static int32_t read_full(int fd, char *buf, size_t n){
	while (n > 0){
		ssize_t rv = read(fd, buf, n);
		if(rv <= 0){
			return -1; //error, or unexpected EOF
		}
		assert((size_t)rv <= n);
		n -= (size_t)rv;
		buf += rv;
	}
	return 0;
}

static int32_t write_all(int fd, const char *buf, size_t n){
	while (n > 0){
		ssize_t rv = write(fd, buf, n);
		if(rv <= 0){
			return -1; // error
		}
		assert((size_t)rv <= n);
		n -= (size_t)rv;
		buf += rv;
	}
	return 0;
}
*/
// process 1 request if there is enough data
static bool try_one_request(Conn *conn){
	// try to parse the protocol: message header
	if (conn->incoming.size() < 4){
		return false; // want read
	}
	uint32_t len = 0;
	memcpy(&len, conn->incoming.data(), 4);
	if(len > k_max_msg){
		msg("too long");
		conn->want_close = true;
		return false; // want close
	}
	// message body
	if ( 4 + len > conn->incoming.size()){
		return false; // want read
	}
	const uint8_t *request = &conn->incoming[4];

	// got one request, do some application logic
	printf("client says: len:%d data:%.*s\n",
					len, len < 100 ? len : 100, request);
	// generate the response (echo)
	buf_append(conn->outgoing, (const uint8_t *)&len, 4);
	buf_append(conn->outgoing, request, len);

	// application logic done! remove the request message
	buf_consume(conn->incoming, 4 + len);
	return true; // success
}
/*
 * handle one msg
static void do_something(int connfd){
	char rbuf[64] = {};
	ssize_t n = read(connfd, rbuf, sizeof(rbuf) - 1);
	if (n < 0){
		msg("read() error");
		return;
	}
	fprintf(stderr, "client says: %s\n", rbuf);
	char wbuf[] = "world";
	write(connfd, wbuf, strlen(wbuf));
}
*/

// application callback when the socket is writable
static void handle_write(Conn *conn){
	assert(conn->outgoing.size() > 0);
	ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
	if (rv < 0 && errno == EAGAIN){
		return; // actually not ready
	}
	if (rv < 0){
		msg_errno("write() error");
		conn->want_close = true; // error handling
		return;
	}

	// remove written data from `outgoing`
	buf_consume(conn->outgoing, (size_t)rv);

	// update the readiness intention
	if (conn->outgoing.size() == 0){ // all data written
		conn->want_read = true;
		conn->want_write = false;
	} // else: want write

}

// application callback when the socket is readable
static void handle_read(Conn *conn){
	// read some data
	uint8_t buf[64 * 1024];
	ssize_t rv = read(conn->fd, buf, sizeof(buf));
	if (rv < 0 && errno == EAGAIN){
		return; // actually not ready
	}
	// handle IO error
	if (rv < 0){
		msg_errno("read() error");
		conn->want_close = true;
		return; // want close
	}
	// handle EOF
	if ( rv == 0){
		if (conn->incoming.size() == 0){
			msg("client closed");
		}else{
			msg("unexpected EOF");
		}
		conn->want_close = true;
		return; // want close
	}
	// get some new data
	buf_append(conn->incoming, buf, (size_t)rv);	

	// parse requests and generate reponses
	while (try_one_request(conn)){
	}
	
	// update the readiness intention
	if (conn->outgoing.size() > 0){
		conn->want_read = false;
		conn->want_write = true;	
		// The socket is likely ready to write in a request-response protocol,
		// try to write it without waiting for the next iteration
		return handle_write(conn);
	} // else: want read

}



int main(){
	// the listening socket
	int fd = socket(AF_INET, SOCK_STREAM, 0);
	if (fd < 0) {
		die("socket()");	
	}
	// this is needed for most server applications
	int val = 1;
	setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

	// bind
	struct sockaddr_in addr = {};

	addr.sin_family = AF_INET;
	addr.sin_port = ntohs(1234);
	addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0
	int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
	if (rv){
		die("bind()");
	}

	// listen
	rv = listen(fd, SOMAXCONN);
	if(rv){
		die("listen()");
	}

	while (true){
		// accept
		struct sockaddr_in client_addr = {};
		socklen_t addrlen = sizeof(client_addr);
		int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
		if (connfd < 0){
			continue;	
		}
		while (true){
			// here the server only serves one client connection at once
			int32_t err = one_request(connfd);
			if (err){
				break;
			}

		}
		close(connfd);
	}
	
	return 0;
}
